# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        pip install poetry
    - name: Install Poetry Deps
      run: |
        poetry install -C example-app
    - name: Lint 
      run: |
        poetry run task lint -C example-app
    - name: Format
      run: |
        poetry run task formatter -C example-app
    - name: Security
      run: |
        poetry run task security -C example-app
    - name: Test
      run: |
        poetry run task test -C example-app
